[package]
name = "ok"
version = "0.1.0"
authors = ["pgray <pgray@ns1.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
criterion = "0.3"

[[bench]]
name = "ok"
harness = false